[CmdletBinding()]
param(
    [string] $Path = (Join-Path (Split-Path $PSScriptRoot -Parent) 'screenshots\IntuneAccess-3.0-preview.html')
)

$moduleRoot = Split-Path $PSScriptRoot -Parent
Import-Module (Join-Path $moduleRoot 'IntuneAccess.psd1') -Force
$generated = [DateTimeOffset]::Parse('2026-08-24T11:30:00+01:00')
$device = [PSCustomObject] @{ Id = 'device-1'; DeviceName = 'CADTB-LAPTOP-023'; UserId = 'user-1'; UserPrincipalName = 'alex.wilber@contoso.example'; UserDisplayName = 'Alex Wilber'; EntraDeviceId = '11111111-1111-1111-1111-111111111111'; OperatingSystem = 'Windows'; OsVersion = '10.0.26100.4946'; ComplianceState = 'noncompliant'; ManagementAgent = 'mdm'; EnrollmentType = 'windowsAutopilot'; LastSyncDateTime = '2026-07-12T09:15:00Z'; EnrolledDateTime = '2026-05-01T10:00:00Z'; Manufacturer = 'Microsoft Corporation'; Model = 'Surface Laptop 6'; SerialNumber = 'CADTB-023-ABC'; Ownership = 'company'; ManagementState = 'registered' }
$workload = [PSCustomObject] @{ Id = 'app-1'; Name = 'Microsoft 365 Apps'; Description = 'Required productivity applications'; WorkloadType = 'Applications'; SourceCollection = 'Applications'; ScopeTagIds = @(); AssignmentDataState = 'Available'; SourceApiVersion = 'v1.0'; AssignmentCount = 1 }
$deviceFinding = [PSCustomObject] @{ FindingId = 'DEV-CHECKIN-STALE/device-1'; Title = 'Stale Intune check-in'; DeviceId = 'device-1'; DeviceName = $device.DeviceName; RuleId = 'DEV-CHECKIN-STALE'; Severity = 'High'; Category = 'Hygiene'; Explanation = 'The last confirmed Intune check-in is 43 days old.'; ReviewRecommendation = 'Confirm whether the device is still in service and investigate client connectivity before considering lifecycle action.'; EvidenceTimestamp = $device.LastSyncDateTime }
$assignmentExplanation = [PSCustomObject] @{ DeviceId = 'device-1'; DeviceName = $device.DeviceName; WorkloadId = 'app-1'; WorkloadName = $workload.Name; WorkloadType = 'Applications'; AssignmentState = 'Included'; ReportedOutcomeState = 'Error'; AssignmentPaths = @([PSCustomObject] @{ TargetType = 'Included group'; PathState = 'Included'; DeviceTargetState = 'Matched'; UserTargetState = 'NotMatched'; FilterState = 'Passed' }); EvidenceBoundary = 'Assignment configuration, group membership, supported filter evaluation and reported outcome are separate evidence layers. Assignment does not prove delivery.' }
$autopilot = [PSCustomObject] @{ AutopilotIdentityId = 'autopilot-1'; ManagedDeviceId = 'device-1'; DeviceName = $device.DeviceName; SerialNumber = $device.SerialNumber; EntraDeviceId = $device.EntraDeviceId; GroupTag = 'Corporate'; EnrollmentState = 'failure'; DeploymentProfileName = 'Windows Corporate'; ProfileAssignmentState = 'assigned'; LastContactedDateTime = '2026-05-01T10:35:00Z'; EventCount = 1; Timeline = @([PSCustomObject] @{ Stage = 'Device preparation'; State = 'success'; DurationSeconds = 125 }, [PSCustomObject] @{ Stage = 'Device setup'; State = 'failure'; DurationSeconds = 842 }, [PSCustomObject] @{ Stage = 'Account setup'; State = 'NotReturned'; DurationSeconds = $null }); FailureDetails = @('Device setup returned failure evidence'); EvidenceBoundary = 'Autopilot and ESP evidence uses Microsoft Graph beta. Missing stages are unavailable evidence, not proof that the stage did not run.' }
$detectedApp = [PSCustomObject] @{ Id = 'detected-1'; DisplayName = 'Microsoft 365 Apps for enterprise'; Publisher = 'Microsoft Corporation'; Version = '16.0.19127.20154'; Platform = 'windows'; ReportedDeviceCount = 18; RelationshipState = 'Available'; ManagedDevices = @([PSCustomObject] @{ Id = 'device-1'; DeviceName = $device.DeviceName }) }
$applicationEvidence = [PSCustomObject] @{ ApplicationId = 'app-1'; ApplicationName = $workload.Name; DeviceId = 'device-1'; DeviceName = $device.DeviceName; ConfiguredIntents = @('required'); InstallResults = @([PSCustomObject] @{ Category = 'Error' }); DetectedSoftware = @(); DetectionState = 'NotDetectedByExactName'; Requirements = @([PSCustomObject] @{ Rule = 'Windows 11' }); DetectionRules = @([PSCustomObject] @{ Rule = 'MSI product code' }); Relationships = @(); EvidenceBoundary = 'Assignment intent, reported installation state and detected software are separate. Exact-name detection is not proof that an Intune detection rule passed. Client logs can be required for root-cause analysis.' }
$updateEvidence = [PSCustomObject] @{ DeviceId = 'device-1'; DeviceName = $device.DeviceName; UserPrincipalName = $device.UserPrincipalName; OperatingSystem = 'Windows'; OsVersion = $device.OsVersion; WorkloadId = 'update-1'; WorkloadName = 'Windows 11 24H2'; WorkloadType = 'Updates'; SourceCollection = 'Feature update policies'; TargetVersion = '24H2'; ReportedState = 'NoReportedEvidence'; InvestigationState = 'StaleReporting'; Explanation = 'The latest managed-device check-in evidence is 43 days old.'; EvidenceAgeDays = 43; EvidenceTimestamp = $device.LastSyncDateTime; EvidenceBoundary = 'Configured targeting, reporting delay, stale evidence, returned failure and unavailable evidence are separate states.' }
$estateFinding = [PSCustomObject] @{ FindingId = 'OUTCOME/app-1/device-1'; PriorityScore = 75; Severity = 'High'; Category = 'Deployment'; Title = 'Reported deployment error: Microsoft 365 Apps'; DeviceId = 'device-1'; DeviceName = $device.DeviceName; SourceType = 'DeploymentOutcome'; SourceId = 'app-1'; EvidenceTimestamp = '2026-07-12T09:10:00Z'; Explanation = 'Intune returned an error-category application result.'; ReviewRecommendation = 'Review the workload result and device-side logs before assigning root cause.'; CauseState = 'NotAsserted' }
$model = [PSCustomObject] @{
    PSTypeName = 'IntuneAccess.TenantRbac'; Tenant = [PSCustomObject] @{ Id = 'tenant-1'; DisplayName = 'Contoso Device Lab' }; GeneratedAt = $generated; ToolVersion = '3.0.0'; InitialUserPrincipalName = ''; GraphPermissionsUsed = @('DeviceManagementManagedDevices.Read.All','Device.Read.All','DeviceManagementApps.Read.All','DeviceManagementConfiguration.Read.All'); Warnings = @('Autopilot evidence uses Microsoft Graph beta and must be reviewed with device-side diagnostics.'); Administrators = @(); AdminGroups = @(); RoleAssignments = @(); RoleDefinitions = @(); ScopeGroups = @(); ScopeTags = @(); Permissions = @(); Memberships = @(); WorkloadObjects = @($workload); WorkloadAssignments = @(); WorkloadGroups = @(); AssignmentFilters = @(); WorkloadCollectionStatus = @(); ManagedDevices = @($device); ManagedUsers = @(); DeploymentOutcomes = @(); OutcomeCollectionStatus = @(); PolicySettings = @(); PolicyConflictFindings = @(); PolicyConflictCollectionStatus = @(); AuditEvents = @(); AuditCollectionStatus = $null; DeviceInventory = @($device); DeviceFindings = @($deviceFinding); DeviceAssignmentExplanations = @($assignmentExplanation); AutopilotTimelines = @($autopilot); DetectedApplications = @($detectedApp); DeviceApplicationEvidence = @($applicationEvidence); UpdateComplianceInvestigations = @($updateEvidence); EstateFindings = @($estateFinding); RecurringFailures = @([PSCustomObject] @{ Signature = 'shared-app-error'; Title = 'Reported deployment error: Microsoft 365 Apps'; SourceType = 'DeploymentOutcome'; SourceId = 'app-1'; DeviceCount = 4; DeviceIds = @('device-1','device-2','device-3','device-4'); FindingIds = @('finding-1','finding-2','finding-3','finding-4'); CauseState = 'NotAsserted'; Explanation = 'These devices share returned evidence. The grouping does not prove a common root cause.' }); DeviceCohorts = @([PSCustomObject] @{ Dimension = 'Model'; Value = 'Surface Laptop 6'; DeviceCount = 12; DeviceIds = @('device-1'); FindingCount = 4 }); CrossDeviceInvestigations = @([PSCustomObject] @{ SourceType = 'DeploymentOutcome'; SourceId = 'app-1'; DeviceCount = 4; DeviceIds = @('device-1','device-2','device-3','device-4'); FindingIds = @('finding-1','finding-2','finding-3','finding-4'); HighestPriority = 75 }); EstateHistoricalTrend = [PSCustomObject] @{ State = 'NoBaseline'; Changes = @(); Explanation = 'No local baseline snapshot was supplied.' }
}

$model | Export-IntuneAccessReport -Path $Path -Force
